spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: financial-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/financial/**
        - id: physical-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/physical/**
        - id: emotional-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/emotional/**
        - id: career-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/career/**
        - id: spiritual-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/spiritual/**
        - id: social-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/social/**
        - id: ai-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/ai/**

server:
  port: 8080